### ISSUE TITLE
invalid `node_list.json`

### ISSUE THREAD

**Issue by ltdrdata** [Dayuppy/ComfyUI-DiscordWebhook#4]
https://github.com/Dayuppy/ComfyUI-DiscordWebhook/blob/4fe9e27d82b50de71c84671a42cfb5ef5d4736f4/node_list.json#L1

That should be json file.

e.g.
https://raw.githubusercontent.com/melMass/comfy_mtb/main/node_list.json

**Comment by Dayuppy** [comment]
> https://github.com/Dayuppy/ComfyUI-DiscordWebhook/blob/4fe9e27d82b50de71c84671a42cfb5ef5d4736f4/node_list.json#L1
> 
> That should be json file.
> 
> e.g. https://raw.githubusercontent.com/melMass/comfy_mtb/main/node_list.json

Hoping I understood this correctly. Pushed commit [350087f](https://github.com/Dayuppy/ComfyUI-DiscordWebhook/commit/350087fe13ea2091737b4a479f9d9acaccfbc9fd)

**Comment by Dayuppy** [comment]
Marking resolved as I have not gotten a reply and it seems to be working after installing from the ComfyUI-Manager.
